type: object

properties:
  codProducto:
    type: string
    description: Código del producto.
  nombre:
    type: string
    description: Nombre del producto.
  descripcion:
    type: string
    description: Descripción del producto.
  precio:
    type: number
    format: double
    description: Precio del producto.
  url_img:
    type: string
    description: url img de cloudinary
